/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Black Snow (https://sketchfab.com/BlackSnow02)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/toyota-supra-mk4-8bebdee25b774067929bb33e648533ac
Title: Toyota Supra mk4
*/

import React, { useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import carScene from "../assets/3d/toyota_supra_mk4.glb";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const ref = useRef();
  const [hovered, setHover] = useState(false);

  const { scene, nodes, materials } = useGLTF(carScene);

  useFrame(({ clock, camera }) => {
    // Update the Y position to simulate bird-like motion using a sine wave
    // ref.current.position.y = Math.sin(clock.elapsedTime) * 0.2;
    // ref.current.rotation.y += 0.02;
    // ref.current.position.z = Math.sin(clock.elapsedTime) * 2;
    if (hovered) ref.current.position.x += 0.02;
    //  ref.current.position.x += 0.1;
    // Check if the bird reached a certain endpoint relative to the camera
  });
  return (
    <mesh {...props} ref={ref} dispose={null}>
      <primitive
        object={scene}
        onPointerOver={(event) => setHover(true)}
        onPointerOut={(event) => setHover(false)}
        onPointer
      />
    </mesh>
  );
}

useGLTF.preload(carScene);
